export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL =  "UPDATE_PASSWORD_FAIL";
export const UPDATE_INFO_SUCCESS = "UPDATE_INFO_SUCCESS";
export const UPDATE_INFO_FAIL = "UPDATE_INFO_FAIL" ;

export const SET_MESSAGE_LOGIN = "SET_MESSAGE_LOGIN";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_MESSAGE_REGISTER = "SET_MESSAGE_REGISTER";
export const SET_MESSAGE_UPDATE_PASSWORD = "SET_MESSAGE_UPDATE_PASSWORD";
export const SET_MESSAGE_UPDATE_INFO = "SET_MESSAGE_UPDATE_INFO";


export const CLEAR_MESSAGE = "CLEAR_MESSAGE";